services:
  cloud-image-repository-development:
    image: "cloud-image-repository:latest"
    container_name: cloud-image-repository-development
    environment:
      DEV_MODE: "${DEV_MODE}"
      SECRET_KEY: "${SECRET_KEY}"
      CLOUD_REPOSITORY_APIKEY: "${CLOUD_REPOSITORY_APIKEY}"
      GITHUB_OAUTH_CLIENT_ID: "${GITHUB_OAUTH_CLIENT_ID}"
      GITHUB_OAUTH_CLIENT_SECRET: "${GITHUB_OAUTH_CLIENT_SECRET}"
      GITHUB_OAUTH_REDIRECT_URL: "${GITHUB_OAUTH_REDIRECT_URL}"
    volumes:
      - ../public:/app/public
      - ../backend:/app/backend
      - ../docker/entrypoint.sh:/app/entrypoint.sh
    ports:
      - "3918:5000"
      - "5173:5173"
      - "5678:5678"
    entrypoint: ["/app/entrypoint.sh"]