name: Create Tag

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Tag version (e.g., 0.0.0)'
        required: true

jobs:
  create_tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Create or update tag
        run: |
          VERSION="${{ github.event.inputs.version }}"
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git tag -f "$VERSION"
          git push origin "$VERSION" --force